[package]
name = "channel_examples"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
ockam = { path = "../../../ockam", version = "*" }
ockam_node = { path = "../../../ockam_node", version = "*" }
ockam_vault_sync_core = { path = "../../../ockam_vault_sync_core", version = "0.1.0" }
ockam_vault = { path = "../../../ockam_vault", version = "0.4.0" }
tracing = "0.1"
ockam_transport_tcp = { path = "../../../ockam_transport_tcp", version = "*" }
tokio = {version = "1.1.0", features = ["rt-multi-thread","sync","net","macros","time"]}
rand = "0.8.3"
